import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71K8H7bWlLL._AC_UX575_.jpg",
    title: "Adidas Ultraboost 21",
    star: <AiFillStar className="rating-star" />,
    reviews: "(98 reviews)",
    prevPrice: "$180.00",
    newPrice: "150",
    company: "Adidas",
    color: "black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71k3fJh5VnL._AC_UX575_.jpg",
    title: "Puma RS-X³ Puzzle",
    star: <AiFillStar className="rating-star" />,
    reviews: "(77 reviews)",
    prevPrice: "$120.00",
    newPrice: "95",
    company: "Puma",
    color: "multi-color",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61Iayt9R7XL._AC_UX575_.jpg",
    title: "Vans Old Skool",
    star: <AiFillStar className="rating-star" />,
    reviews: "(210 reviews)",
    prevPrice: "$75.00",
    newPrice: "60",
    company: "Vans",
    color: "black",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71z8B2rGtgL._AC_UX575_.jpg",
    title: "Converse Chuck Taylor All Star",
    star: <AiFillStar className="rating-star" />,
    reviews: "(300 reviews)",
    prevPrice: "$65.00",
    newPrice: "55",
    company: "Converse",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71vG7NnGRpL._AC_UX575_.jpg",
    title: "Reebok Classic Leather",
    star: <AiFillStar className="rating-star" />,
    reviews: "(150 reviews)",
    prevPrice: "$85.00",
    newPrice: "70",
    company: "Reebok",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zCUl0SYeL._AC_UX575_.jpg",
    title: "Asics Gel-Kayano 27",
    star: <AiFillStar className="rating-star" />,
    reviews: "(132 reviews)",
    prevPrice: "$160.00",
    newPrice: "130",
    company: "Asics",
    color: "blue",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71qT4d0fl6L._AC_UX575_.jpg",
    title: "New Balance 574",
    star: <AiFillStar className="rating-star" />,
    reviews: "(180 reviews)",
    prevPrice: "$100.00",
    newPrice: "85",
    company: "New Balance",
    color: "grey",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71HblUlcQnL._AC_UX575_.jpg",
    title: "Nike Air Force 1",
    star: <AiFillStar className="rating-star" />,
    reviews: "(400 reviews)",
    prevPrice: "$110.00",
    newPrice: "95",
    company: "Nike",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/81wp6u42QlL._AC_UX575_.jpg",
    title: "Adidas Stan Smith",
    star: <AiFillStar className="rating-star" />,
    reviews: "(350 reviews)",
    prevPrice: "$90.00",
    newPrice: "75",
    company: "Adidas",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/81a2Y2lPqLL._AC_UX575_.jpg",
    title: "Nike Air Max 270",
    star: <AiFillStar className="rating-star" />,
    reviews: "(270 reviews)",
    prevPrice: "$150.00",
    newPrice: "130",
    company: "Nike",
    color: "red",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71f0lf6eGrL._AC_UX575_.jpg",
    title: "Puma Suede Classic",
    star: <AiFillStar className="rating-star" />,
    reviews: "(200 reviews)",
    prevPrice: "$70.00",
    newPrice: "55",
    company: "Puma",
    color: "green",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/81V+lM2fn7L._AC_UX575_.jpg",
    title: "Nike ZoomX Vaporfly",
    star: <AiFillStar className="rating-star" />,
    reviews: "(190 reviews)",
    prevPrice: "$250.00",
    newPrice: "220",
    company: "Nike",
    color: "pink",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/81G6jWbtHLL._AC_UX575_.jpg",
    title: "Skechers Go Walk Evolution",
    star: <AiFillStar className="rating-star" />,
    reviews: "(145 reviews)",
    prevPrice: "$80.00",
    newPrice: "65",
    company: "Skechers",
    color: "black",
    category: "walking",
  },
  {
    img: "https://m.media-amazon.com/images/I/71m2Rjk4QmL._AC_UX575_.jpg",
    title: "Fila Disruptor II",
    star: <AiFillStar className="rating-star" />,
    reviews: "(90 reviews)",
    prevPrice: "$95.00",
    newPrice: "80",
    company: "Fila",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/81p53bmn7JL._AC_UX575_.jpg",
    title: "Jordan Retro 1 High",
    star: <AiFillStar className="rating-star" />,
    reviews: "(500 reviews)",
    prevPrice: "$170.00",
    newPrice: "150",
    company: "Nike",
    color: "black-red",
    category: "basketball",
  },
  {
    img: "https://m.media-amazon.com/images/I/81Z4ShJZL6L._AC_UX575_.jpg",
    title: "Nike Blazer Mid '77",
    star: <AiFillStar className="rating-star" />,
    reviews: "(250 reviews)",
    prevPrice: "$105.00",
    newPrice: "90",
    company: "Nike",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71rY9hL4NPL._AC_UX575_.jpg",
    title: "Adidas Yeezy Boost 350",
    star: <AiFillStar className="rating-star" />,
    reviews: "(700 reviews)",
    prevPrice: "$300.00",
    newPrice: "280",
    company: "Adidas",
    color: "beige",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71rUdswZgtL._AC_UX575_.jpg",
    title: "Under Armour Charged Assert 9",
    star: <AiFillStar className="rating-star" />,
    reviews: "(120 reviews)",
    prevPrice: "$85.00",
    newPrice: "70",
    company: "Under Armour",
    color: "blue",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/81E8F84WZ0L._AC_UX575_.jpg",
    title: "Brooks Ghost 13",
    star: <AiFillStar className="rating-star" />,
    reviews: "(110 reviews)",
    prevPrice: "$130.00",
    newPrice: "115",
    company: "Brooks",
    color: "grey",
    category: "running",
  },
];
